version: '3.8'

services:
  eXit:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
        - "24:24"
    container_name: eXit-Game
    restart: unless-stopped
    command: go run .

